'use strict';

/** Sample catalogue used by the seed script. Images are royalty-free Unsplash URLs. */
module.exports = [
  {
    name: 'Fresh Boneless Chicken Breast',
    description:
      'Skinless, boneless breast fillets from farm-raised broilers. Cut and chilled the same morning, vacuum packed for freshness.',
    category: 'Fresh Meat',
    price: 620,
    unit: 'kg',
    stock: 40,
    tags: ['chicken', 'boneless', 'lean'],
    images: ['https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=800&q=80'],
  },
  {
    name: 'Whole Country Chicken (Local)',
    description:
      'Free-range local chicken (sakhuwa), cleaned and cut on request. Firmer texture and deeper flavour than broiler.',
    category: 'Fresh Meat',
    price: 890,
    unit: 'kg',
    stock: 22,
    tags: ['chicken', 'local', 'free-range'],
    images: ['https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=800&q=80'],
  },
  {
    name: 'Goat Meat (Khasi) — Curry Cut',
    description:
      'Premium Khasi mutton in bone-in curry cuts. Sourced from Nepali highland farms and butchered fresh daily.',
    category: 'Fresh Meat',
    price: 1450,
    unit: 'kg',
    stock: 18,
    tags: ['mutton', 'khasi', 'curry cut'],
    images: ['https://images.unsplash.com/photo-1603048297172-c92544798d5a?w=800&q=80'],
  },
  {
    name: 'Buff Boneless (Buffalo Meat)',
    description: 'Lean boneless buffalo meat, trimmed of excess fat. Ideal for choila, sekuwa, and slow curries.',
    category: 'Fresh Meat',
    price: 540,
    unit: 'kg',
    stock: 35,
    tags: ['buff', 'buffalo', 'boneless'],
    images: ['https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800&q=80'],
  },
  {
    name: 'Pork Belly — Skin On',
    description: 'Layered pork belly with the skin on, cut into thick slabs. Perfect for roasting and Nepali pork curry.',
    category: 'Fresh Meat',
    price: 780,
    unit: 'kg',
    stock: 16,
    tags: ['pork', 'belly'],
    images: ['https://images.unsplash.com/photo-1602470521006-aeff0d956b5c?w=800&q=80'],
  },
  {
    name: 'Chicken Sausages (Pack of 10)',
    description: 'Mildly spiced chicken sausages, nitrite-free, ready in five minutes on a pan or grill.',
    category: 'Processed Meat',
    price: 460,
    unit: 'pack',
    stock: 50,
    tags: ['sausage', 'chicken', 'ready to cook'],
    images: ['https://images.unsplash.com/photo-1597645587822-e99fa5d45d25?w=800&q=80'],
  },
  {
    name: 'Smoked Buff Salami — 250 g',
    description: 'Slow-smoked buffalo salami, thinly sliced. A Kathmandu deli favourite for sandwiches and pizza.',
    category: 'Processed Meat',
    price: 395,
    unit: 'pack',
    stock: 30,
    tags: ['salami', 'smoked', 'buff'],
    images: ['https://images.unsplash.com/photo-1588347818133-2b1a1b0b4b6e?w=800&q=80'],
  },
  {
    name: 'Chicken Momo Keema — 500 g',
    description: 'Finely minced chicken with ginger, garlic, and spring onion — the base for restaurant-style momo.',
    category: 'Processed Meat',
    price: 340,
    unit: 'pack',
    stock: 45,
    tags: ['keema', 'momo', 'minced'],
    images: ['https://images.unsplash.com/photo-1626074353765-517a681e40be?w=800&q=80'],
  },
  {
    name: 'Tandoori Marinated Chicken — 1 kg',
    description: 'Bone-in chicken marinated overnight in yoghurt, kashmiri chilli, and tandoori masala. Oven ready.',
    category: 'Marinated',
    price: 720,
    unit: 'kg',
    stock: 25,
    tags: ['tandoori', 'marinated', 'ready to cook'],
    images: ['https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=800&q=80'],
  },
  {
    name: 'Sekuwa Marinated Mutton — 500 g',
    description: 'Khasi cubes marinated in timur, mustard oil, and Nepali herbs. Grill over charcoal for authentic sekuwa.',
    category: 'Marinated',
    price: 850,
    unit: 'pack',
    stock: 20,
    tags: ['sekuwa', 'mutton', 'marinated'],
    images: ['https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80'],
  },
  {
    name: 'Goat Liver (Kalejo) — 500 g',
    description: 'Fresh goat liver, cleaned and cubed. Rich in iron and a staple of Newari fry preparations.',
    category: 'Offal',
    price: 620,
    unit: 'pack',
    stock: 14,
    tags: ['liver', 'offal', 'kalejo'],
    images: ['https://images.unsplash.com/photo-1608500218890-c4914d0d4f8b?w=800&q=80'],
  },
  {
    name: 'Fresh Rainbow Trout — Whole',
    description: 'Cold-water trout from Nuwakot farms, gutted and cleaned. Delivered on ice within hours of harvest.',
    category: 'Seafood',
    price: 1250,
    unit: 'kg',
    stock: 12,
    tags: ['fish', 'trout', 'seafood'],
    images: ['https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&q=80'],
  },
];
